apiVersion: v1
kind: Service
metadata:
  name: kubecost
  namespace: kubecost
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
  selector:
    app: cost-analyzer